/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KepletekRouteImport } from './routes/kepletek'
import { Route as TablaRouteImport } from './routes/tabla'
import { Route as JegyzetSlugRouteImport } from './routes/jegyzet.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KepletekRoute = KepletekRouteImport.update({
  id: '/kepletek',
  path: '/kepletek',
  getParentRoute: () => rootRouteImport,
} as any)
const TablaRoute = TablaRouteImport.update({
  id: '/tabla',
  path: '/tabla',
  getParentRoute: () => rootRouteImport,
} as any)
const JegyzetSlugRoute = JegyzetSlugRouteImport.update({
  id: '/jegyzet/$slug',
  path: '/jegyzet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kepletek': typeof KepletekRoute
  '/tabla': typeof TablaRoute
  '/jegyzet/$slug': typeof JegyzetSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kepletek': typeof KepletekRoute
  '/tabla': typeof TablaRoute
  '/jegyzet/$slug': typeof JegyzetSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kepletek': typeof KepletekRoute
  '/tabla': typeof TablaRoute
  '/jegyzet/$slug': typeof JegyzetSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kepletek' | '/tabla' | '/jegyzet/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kepletek' | '/tabla' | '/jegyzet/$slug'
  id: '__root__' | '/' | '/kepletek' | '/tabla' | '/jegyzet/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KepletekRoute: typeof KepletekRoute
  TablaRoute: typeof TablaRoute
  JegyzetSlugRoute: typeof JegyzetSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kepletek': {
      id: '/kepletek'
      path: '/kepletek'
      fullPath: '/kepletek'
      preLoaderRoute: typeof KepletekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabla': {
      id: '/tabla'
      path: '/tabla'
      fullPath: '/tabla'
      preLoaderRoute: typeof TablaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jegyzet/$slug': {
      id: '/jegyzet/$slug'
      path: '/jegyzet/$slug'
      fullPath: '/jegyzet/$slug'
      preLoaderRoute: typeof JegyzetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KepletekRoute: KepletekRoute,
  TablaRoute: TablaRoute,
  JegyzetSlugRoute: JegyzetSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
